### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by hoovercj** [nanreh/calendar-hack#12]
I did a quick test using [Accessibility Insights](https://accessibilityinsights.io/docs/en/web/overview/) and manually checking a few things and here's a list of issues I found:

* [ ] H3 is used to style text "ending on" even though it is a label for an input element, not a true heading. Suggestion is to replace \<h3> with a <label> with an id and add it as the "for" attribute on the input element
* [ ] Home/Github/About links don't have labels (need a "title" attribute or "aria-label" attribute)
* [ ] The "select" element for workouts should have an aria label
* [ ] Mi/Km radio buttons should be in a radio group with an aria label
* [ ] Keyboard focus isn't visible on the workout select dropdown, unit radio buttons, or the "Download" button
* [ ] Date text on purple doesn't meet wcag color contrast requirements. The text should be a bit darker or the purple should be a bit lighter. [This tool](https://dequeuniversity.com/color-contrast) allows checking for AA levels.
![image](https://user-images.githubusercontent.com/2957173/114180288-4c2e6e00-9940-11eb-8bbc-eac6842ed033.png)
* [ ] Unable to reorder items with the keyboard. Suggestion is to make each calendar day focusable (or an element inside focusable) and allow keyboard shortcuts such as arrow keys or some other combination of keys to reorder them.

I'd be happy to submit a PR to fix some of these issues

**Comment by nanreh** [comment]
That would be amazing, thank you for running that check. Would love to address any accessibility issues.
