### ISSUE TITLE
Error in pfitz_18_55.csv

### ISSUE THREAD

**Issue by geashby** [nanreh/calendar-hack#35]
Error in calendar-hack/public/plans/csv/pfitz_18_55.csv, line 62

The distance is not entered as a variable, but as plain text, and the mi-km conversion in the plain text is incorrect

Line reads: `"Long run 18 mi (34 km)","",18`
Line should read: `"Long run {18}","",18`

**Comment by nanreh** [comment]
Nice catch, thank you for pointing it out. Fixed.
