### ISSUE TITLE
Option to change date format from MM/DD/YY to DD/MM/YY or other based on LOCALE

### ISSUE THREAD

**Issue by martiniburningsky** [nanreh/calendar-hack#5]
Great project. I am a runner based in the UK and we use DD/MM/YY date format rather than MM/DD/YY. Would it be possible to add an option to change the date format in the web app or automatically format this according to user locale? Thanks for your work.
Ian

**Comment by nanreh** [comment]
Finally had a chance to do this, sorry it took ages.

80ca96047ba836db716b8c5f275cfaed56b5223b

Dates will be formatted based on locale settings with `Intl.DateTimeFormat(navigator.language)`.

Also added simple code that attempts to default units to something reasonable given `navigator.language`. #

**Comment by martiniburningsky** [comment]
Thank you so much!

From: nanreh ***@***.***>
Date: Saturday, 12 October 2024 at 16:00
To: nanreh/calendar-hack ***@***.***>
Cc: martiniburningsky ***@***.***>, Author ***@***.***>
Subject: Re: [nanreh/calendar-hack] Option to change date format from MM/DD/YY to DD/MM/YY or other based on LOCALE (#5)

Finally had a chance to do this, sorry it took ages.

80ca960<https://github.com/nanreh/calendar-hack/commit/80ca96047ba836db716b8c5f275cfaed56b5223b>

Dates will be formatted based on locale settings with Intl.DateTimeFormat(navigator.language).

Also added simple code that attempts to default units to something reasonable given navigator.language. #
