### ISSUE TITLE
Option to change the first day of the week (Sunday instead of Monday)

### ISSUE THREAD

**Issue by ilalevy** [nanreh/calendar-hack#8]
Great Project!

In Israel the first day of the week is Sunday (usually long runs on Saturday).
Will be great if we can pick the first day of the week according to user preferences.

**Comment by nanreh** [comment]
There's an option now to select the day the week should start on. Most training plans assume a Sunday race so it may take a little bit of messing with the `ending on` date to get the workouts to align the way you want them to on the resulting calendar view... and then make whatever edits you need to for the final date(s) so your race/final week looks the way you want it to.
I looked into setting the value by default by inspecting available language+locale hints and decided not to pursue it... looks like that's actually a fuzzy problem so exposing it as an explicit choice seemed like the right move for now (default behavior is to start the week on Monday).
Sorry this took so long to get to!
